---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.indexer.name }}
  labels:
    {{ toYaml .Values.indexer.labels | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{ toYaml .Values.indexer.labels | nindent 4 }}
  ports:
    - name: splunkweb
      port: {{ .Values.global.splunk.containerPorts.web }}
      targetPort: {{ .Values.global.splunk.containerPorts.web }}
    - name: splunkd
      port: {{ .Values.global.splunk.containerPorts.mgmt }}
      targetPort: {{ .Values.global.splunk.containerPorts.mgmt }}
    - name: replication
      port: {{ .Values.global.splunk.containerPorts.replica }}
      targetPort: {{ .Values.global.splunk.containerPorts.replica }}
    - name: s2s
      port: {{ .Values.global.splunk.containerPorts.s2s }}
      targetPort: {{ .Values.global.splunk.containerPorts.s2s }}
    - name: hec
      port: {{ .Values.global.splunk.containerPorts.hec }}
      targetPort: {{ .Values.global.splunk.containerPorts.hec }}
