---
apiVersion: v1
kind: Service
metadata:
  name: indexer 
  labels:
    app: splunk
    role: splunk_indexer
    tier: indexer 
spec:
  selector:
    app: splunk
    role: splunk_indexer
    tier: indexer
  ports:
    - name: splunkweb
      port: 8000
      targetPort: 8000
    - name: splunkd
      port: 8089
      targetPort: 8089
    - name: replication
      port: 4001
      targetPort: 4001
    - name: s2s
      port: 9997
      targetPort: 9997
    - name: hec
      port: 8088
      targetPort: 8088
  clusterIP: None
