apiVersion: v2
name: chart-splunk
description: Splunk is a horizontal technology used for application management, security and compliance, as well as business and web analytics.
icon: https://avatars.githubusercontent.com/u/651467?s=200&v=4
type: application

version: 0.1.0

appVersion: "0.1.0"
