global:
  namespace: splunk

  splunk:
    password: helloworld

    containerPorts:
      web: 8000
      mgmt: 8089
      kv: 8191
      replica: 4001
      s2s: 9997
      hec: 8088

    image:
      repository: splunk/splunk
      tag: 8.1.1
      pullPolicy: IfNotPresent

nginx:
  name: nginx
  replicas: 1
  containerPort: 80

  labels:
    app: splunk
    role: splunk_defaults
    tier: management

  image:
    repository: nginx
    tag: 1.19.7
    pullPolicy: IfNotPresent

deployer:
  name: deployer
  replicas: 1

  labels:
    app: splunk
    role: splunk_deployer
    tier: management

indexer:
  name: indexer
  replicas: 3

  labels:
    app: splunk
    role: splunk_indexer
    tier: indexer 

license:
  name: license
  replicas: 1

  labels:
    app: splunk
    role: splunk_license_master
    tier: management

master:
  name: master
  replicas: 1

  labels:
    app: splunk
    role: splunk_cluster_master
    tier: management

search:
  captain:
    name: captain
    replicas: 1

    labels:
      app: splunk
      role: splunk_search_head_captain
      tier: search

  member:
    name: search
    replicas: 3

    labels:
      app: splunk
      role: splunk_search_head
      tier: search 
