---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.search.captain.name }}
  labels:
    {{ toYaml .Values.search.captain.labels | nindent 4 }}
spec:
  replicas: {{ .Values.search.captain.replicas }}
  selector:
    matchLabels:
      {{ toYaml .Values.search.captain.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.search.captain.labels | nindent 8 }}
    spec:
      hostname: {{ .Values.search.captain.name }}
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - indexer.splunk.svc.cluster.local
          - search.splunk.svc.cluster.local
      containers:
        - name: {{ .Values.search.captain.name }}
          image: "{{ .Values.global.splunk.image.repository }}:{{ .Values.global.splunk.image.tag }}"
          imagePullPolicy: {{ .Values.global.splunk.image.pullPolicy }}
          env:
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_DEFAULTS_URL
              value: http://{{ .Values.nginx.name }}/default.yml
            - name: SPLUNK_ROLE
              value: splunk_search_head_captain
            - name: SPLUNK_PASSWORD
              value: {{ .Values.global.splunk.password }}
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_CLUSTER_MASTER_URL
              value: master
            - name: SPLUNK_INDEXER_URL
              value: indexer-0,indexer-1,indexer-2 
            - name: SPLUNK_SEARCH_HEAD_URL
              value: search 
            - name: SPLUNK_DEPLOYER_URL
              value: deployer
            - name: SPLUNK_SEARCH_HEAD_CAPTAIN_URL
              value: captain
            - name: DEBUG
              value: "true"
          ports:
            - name: web
              containerPort: {{ .Values.global.splunk.containerPorts.web }}
            - name: mgmt
              containerPort: {{ .Values.global.splunk.containerPorts.mgmt }}
            - name: shc
              containerPort: {{ .Values.global.splunk.containerPorts.replica }}
            - name: kv
              containerPort: {{ .Values.global.splunk.containerPorts.kv }}
          volumeMounts:
            - name: splunk-captain-data
              mountPath: /opt/splunk/var
            - name: splunk-captain-config
              mountPath: /opt/splunk/etc
      volumes:
        - name: splunk-captain-config
          emptyDir: {}
        - name: splunk-captain-data
          emptyDir: {}
