{{- if .Values.global.splunk.daemonset.search -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.search.member.name }}
  labels:
    {{ toYaml .Values.search.member.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.search.member.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.search.member.labels | nindent 8 }}
    spec:
{{- if .Values.search.member.tolerations }}
      tolerations:
{{ toYaml .Values.search.member.tolerations | indent 8 }}
{{- end }}
{{- if .Values.search.member.affinity }}
      affinity:
{{ toYaml .Values.search.member.affinity | indent 8 }}
{{- end }}
      dnsPolicy: ClusterFirst 
      dnsConfig:
        searches: 
          - indexer.splunk.svc.cluster.local
          - search.splunk.svc.cluster.local 
      containers:
        - name: {{ .Values.search.member.name }}
          image: "{{ .Values.global.splunk.image.repository }}:{{ .Values.global.splunk.image.tag }}"
          imagePullPolicy: {{ .Values.global.splunk.image.pullPolicy }}
          env:
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_DEFAULTS_URL
              value: http://{{ .Values.nginx.name }}/default.yml
            - name: SPLUNK_PASSWORD
              value: {{ .Values.global.splunk.password }}
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_ROLE
              value: splunk_search_head
            - name: SPLUNK_CLUSTER_MASTER_URL
              value: master
            - name: SPLUNK_INDEXER_URL
              value: indexer-0,indexer-1,indexer-2
            - name: SPLUNK_SEARCH_HEAD_URL
              value: search,search,search
            - name: SPLUNK_DEPLOYER_URL
              value: deployer
            - name: SPLUNK_SEARCH_HEAD_CAPTAIN_URL
              value: captain
            - name: DEBUG
              value: "true"
            - name: SPLUNK_LAUNCH_CONF
              value: "OPTIMISTIC_ABOUT_FILE_LOCKING=1"
          ports:
            - containerPort: {{ .Values.global.splunk.containerPorts.hec }}
            - containerPort: {{ .Values.global.splunk.containerPorts.mgmt }}
            - containerPort: {{ .Values.global.splunk.containerPorts.kv }} 
            - containerPort: {{ .Values.global.splunk.containerPorts.replica }} 
          volumeMounts:
            - name: splunk-search-config
              mountPath: /opt/splunk/etc
            - name: splunk-search-data
              mountPath: /opt/splunk/var
      volumes:
        - name: splunk-search-config
          hostPath:
            path: /opt/splunk/etc
            type: DirectoryOrCreate
        - name: splunk-search-data
          hostPath:
            path: /opt/splunk/var
            type: DirectoryOrCreate
{{- end }}
