apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    {{ toYaml .Values.nginx.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.nginx.name }}
  replicas: {{ .Values.nginx.replicas }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.nginx.labels | nindent 8 }}
        name: {{ .Values.nginx.name }}
    spec:
      containers:
      - name: {{ .Values.nginx.name }}
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nginx.containerPort }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-data-www
          mountPath: /data/www
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config 
      - name: nginx-data-www
        configMap: 
          name: nginx-data-www 
