---
apiVersion: v1
kind: Service
metadata:
  name: splunk-defaults 
  labels:
    app: splunk
    role: splunk-defaults
    tier: management 
spec:
  selector:
    name: splunk-defaults
  ports:
    - name: nginx-web
      port: 80
      targetPort: 80
  clusterIP: None
