---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ toYaml .Values.nginx.labels | nindent 4 }}
spec:
  type: NodePort
  selector:
    name: {{ .Values.nginx.name }}
  ports:
    - name: nginx-web
      port: {{ .Values.nginx.containerPort }}
      targetPort: {{ .Values.nginx.containerPort }}
