---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.license.name }}
  labels:
    {{ toYaml .Values.license.labels | nindent 4 }}
spec:
  replicas: {{ .Values.license.replicas }}
  selector:
    matchLabels:
      {{ toYaml .Values.license.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ toYaml .Values.license.labels | nindent 8 }}
    spec:
      hostname: {{ .Values.license.name }}
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - indexer.splunk.svc.cluster.local
          - search.splunk.svc.cluster.local
      containers:
        - name: {{ .Values.license.name }}
          image: "{{ .Values.global.splunk.image.repository }}:{{ .Values.global.splunk.image.tag }}"
          imagePullPolicy: {{ .Values.global.splunk.image.pullPolicy }}
          env:
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_DEFAULTS_URL
              value: http://{{ .Values.nginx.name }}/default.yml
            - name: SPLUNK_ROLE
              value: splunk_license_master
            - name: SPLUNK_LICENSE_URI
              value: http://{{ .Values.nginx.name }}/mySplunkLicense.lic
            - name: SPLUNK_PASSWORD
              value: {{ .Values.global.splunk.password }}
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_CLUSTER_MASTER_URL
              value: master
            - name: SPLUNK_INDEXER_URL
              value: indexer-0,indexer-1,indexer-2 
            - name: SPLUNK_SEARCH_HEAD_URL
              value: search-0,search-1
            - name: SPLUNK_DEPLOYER_URL
              value: deployer
            - name: SPLUNK_SEARCH_HEAD_CAPTAIN_URL
              value: captain
            - name: DEBUG
              value: "true"
          ports:
            - name: web
              containerPort: {{ .Values.global.splunk.containerPorts.web }}
            - name: mgmt
              containerPort: {{ .Values.global.splunk.containerPorts.mgmt }}
          volumeMounts:
            - name: splunk-license-data
              mountPath: /opt/splunk/var
            - name: splunk-license-config
              mountPath: /opt/splunk/etc
      volumes:
        - name: splunk-license-config
          emptyDir: {}
        - name: splunk-license-data
          emptyDir: {}
