---
apiVersion: v1
kind: Service
metadata:
  name: master
  labels:
    app: splunk
    role: splunk_cluster_master
    tier: management 
spec:
  selector:
    app: splunk
    role: splunk_cluster_master
    tier: management
  ports:
    - name: splunkweb
      port: 8000
      targetPort: 8000
    - name: splunkd
      port: 8089
      targetPort: 8089
  clusterIP: None
